hardware:
    buttons:
        main_button:
            alias: MAIN_BUTTON
            gpio_bcm: 17
            press_timers:
                long: 10
                short: 4
    leds:
        cloud:
            alias: CLOUD
            gpio_bcm: 10
            initial_state: "OFF"
            os_path: /sys/class/leds/gpio10/
        local_network:
            alias: LOCAL_NETWORK
            gpio_bcm: 27
            initial_state: "OFF"
            os_path: /sys/class/leds/gpio27/
        power:
            alias: POWER
            gpio_bcm: 22
            initial_state: BLINK
            os_path: /sys/class/leds/gpio22/
        
service:
    apis:
        supervisor:
            address: http://127.0.0.1:48484/v2/local/device
    broker:
        address: mqtt://0.0.0.0:1883
    logs:
        level: DEBUG
    rpc:
        http_port: 61665
timers:
    led_overrides:
        open_ap: 15
    led_states:
        blink_down: 1000
        blink_up: 1000
        flick_down: 125
        flick_up: 125
