hardware:
    interface:
        leds:
            cloud:
                alias: CLOUD
                gpio_bcm: 10
                initial_state: "OFF"
                os_path: /sys/class/leds/Green_2
            local_network:
                alias: LOCAL_NETWORK
                gpio_bcm: 27
                initial_state: "OFF"
                os_path: /sys/class/leds/Green_1
service:
    apis:
        supervisor:
            address: http://127.0.0.1:48484/v2/local/device
    logs:
        level: DEBUG
    rpc:
        http_port: 61665
timers:
    led_overrides:
        open_ap: 15
    led_states:
        blink_down: 1000
        blink_up: 1000
        flick_down: 125
        flick_up: 125
